services:
  backend:
    build: ./Backend
    container_name: webresep-backend
    ports:
      - "5000:5000"
    volumes:
      - ./Backend/uploads:/app/uploads
    env_file:
      - ./Backend/.env
    depends_on:
      - mongodb

  frontend:
    build: ./Frontend
    container_name: webresep-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongodb:
    image: mongo:6
    container_name: mongo-resep
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-resep
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 5

volumes:
  mongo_data:
